"""fix a user - post relationship

Revision ID: 68b6ac89127f
Revises: 52ef7b94c6df
Create Date: 2022-04-25 03:15:52.960373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b6ac89127f'
down_revision = '52ef7b94c6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'posts_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posts_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
